### ISSUE TITLE
Not working since flutter latest update?

### ISSUE THREAD

**Issue by ceojazzy** [vdung7/startapp_flutter_plugin#1]
Hi, the app is crashing when i add this dependency in the pubsec

**Comment by vdung7** [comment]
Hi, could you give more information about your case? (crash log, flutter version, etc.)

Many thanks

**Comment by vdung7** [comment]
May your problem is fixed from version 0.2.0
Please update the plugin version in pubspec.yaml and try again.

Many thanks
