### ISSUE TITLE
App Crashes on startup with error java.lang.UnsupportedOperationException flutter

### ISSUE THREAD

**Issue by ahmedthinkdifferent** [vdung7/startapp_flutter_plugin#4]
why app crash on startup with error java.lang.UnsupportedOperationException flutter
i think it's need upgrade flutter version.

**Comment by glennmichaelmejias** [comment]
@ahmedthinkdifferent did you fix it?

**Comment by ahmedthinkdifferent** [comment]
@glennmichaelmejias  i solved it and push new commit
