### ISSUE TITLE
 The new embedding does not support the old FlutterView.

### ISSUE THREAD

**Issue by jakcal** [vdung7/startapp_flutter_plugin#6]
I have a new Flutter version and I get this error :  The new embedding does not support the old FlutterView.
Please fix.

**Comment by fadhlanfauzanudien** [comment]
@jakcal  Try change file in {flutter installation folder}/.pub-cache/hosted/pub.dartlang.org/startapp-0.3.0+1
go to android/src/main/main/java/vn/momo/plugin/startapp
edit StartAppBannerPlugin
on line 59 
change
`final MethodChannel channel = new MethodChannel(registrar.view(), "flutter_startapp");`
to
`final MethodChannel channel = new MethodChannel(registrar.messenger(), "flutter_startapp");`
and save. it works for me

**Comment by vdung7** [comment]
Thank @fadhlanfauzanudien for indicate the problem.
@jakcal Could you try upgrade version 0.4.0 which upgrade the plugin to support new plugin API (https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)
