### ISSUE TITLE
not adding this package in my pubspec.yaml

### ISSUE THREAD

**Issue by Sreejith93** [vdung7/startapp_flutter_plugin#7]
[startapp] flutter packages get
Running "flutter pub get" in startapp...                        
Error on line 23, column 3 of pubspec.yaml: A package may not list itself as a dependency.

   ╷
23 │   startapp: ^0.4.0
   │   ^^^^^^^^
   ╵
pub get failed (65;    ╵)
exit code 65

i got this error

**Comment by vdung7** [comment]
Hi @Sreejith93,

I'm guessing the name of your flutter project is also `startapp`.
```
name: startapp

dependencies:
  startapp: ^0.4.0
```
Can you check if that's the case and if not could you please include the full pubspec.yaml file?

Thanks!

**Comment by Sreejith93** [comment]
> Hi @Sreejith93,
> 
> I'm guessing the name of your flutter project is also `startapp`.
> 
> ```
> name: startapp
> 
> dependencies:
>   startapp: ^0.4.0
> ```
> 
> Can you check if that's the case and if not could you please include the full pubspec.yaml file?
> 
> Thanks!

thank you. its correct
