### ISSUE TITLE
[REQ] Splash AD

### ISSUE THREAD

**Issue by renanrrs** [vdung7/startapp_flutter_plugin#8]
Hi! Thanks for the plugin. 
Would it be possible to put an option to enable Splash AD, which is enabled by default?
I believe that an option to activate or not the line:
StartAppAd.disableSplash ();

**Comment by vdung7** [comment]
Sure @renanrrs, thank you for your idea

**Comment by vdung7** [comment]
Hey @renanrrs, please check new release 0.5.0 for setting up the Splash ad
